import { readFile, writeFile, rename, mkdir } from 'node:fs/promises';
import { dirname } from 'node:path';
import { createHash } from 'node:crypto';
const CURATE_FILE = process.env.CURATE_FILE || `${process.env.DATA_DIR || '/data'}/curate.json`;
const LICENSES=['MIT','Apache-2.0','BSD-3-Clause','CC-BY-4.0','CC0-1.0','proprietary','other'];
const ALLOWED=new Set(['item_id','kind','source','license','provenance','quality_score','decision','reviewer','submitted_by','ts','notes']);
const FORBIDDEN=new Set(['value','secret','token','password','api_key','key']);
export function scrub(input){ const rec={}; for(const [k,v] of Object.entries(input||{})){ const key=String(k).toLowerCase(); if(FORBIDDEN.has(key)) throw new Error(`refused: "${k}" — metadata only`); if(!ALLOWED.has(key)) continue; rec[key]=v; } if(!rec.item_id) throw new Error('requires an "item_id"'); rec.kind=rec.kind||'content'; rec.decision=rec.decision||'pending'; return rec; }
async function load(){ try{ const j=JSON.parse(await readFile(CURATE_FILE,'utf8')); return {items:j.items||[]}; }catch{ return {items:[]}; } }
async function save(s){ await mkdir(dirname(CURATE_FILE),{recursive:true}).catch(()=>{}); const t=CURATE_FILE+'.tmp'; await writeFile(t,JSON.stringify(s,null,2)); await rename(t,CURATE_FILE); }
export async function listItems(decision){ const {items}=await load(); return {items:decision?items.filter(i=>i.decision===decision):items,count:items.length}; }
export async function submit(input){ const rec=scrub({...input,decision:'pending',ts:input.ts||new Date().toISOString()}); const s=await load(); const i=s.items.findIndex(x=>x.item_id===rec.item_id); if(i>=0)s.items[i]={...s.items[i],...rec}; else s.items.push(rec); await save(s); return rec; }
export async function decide(item_id,decision,reviewer){ if(!['accepted','rejected'].includes(decision))throw new Error('decision must be accepted or rejected'); const s=await load(); const it=s.items.find(x=>x.item_id===item_id); if(!it)throw new Error(`no item "${item_id}"`); if(decision==='accepted'){ if(!it.license||!LICENSES.includes(it.license))throw new Error('cannot accept without a known license'); if(!it.provenance)throw new Error('cannot accept without provenance'); } it.decision=decision; it.reviewer=reviewer||'steward'; it.decided_at=new Date().toISOString(); await save(s); return it; }
function readJson(req){ return new Promise(r=>{let b='';req.on('data',c=>b+=c);req.on('end',()=>{try{r(b?JSON.parse(b):{})}catch{r({})}})}); }
function sendJson(res,c,o){ res.writeHead(c,{'content-type':'application/json'}); res.end(JSON.stringify(o)); }
export async function curate(req,res,ctx={}){ const json=ctx.json||((c,o)=>sendJson(res,c,o)); const me=ctx.identity&&ctx.identity.login; try{ if(req.method==='GET')return json(200,await listItems()); if(req.method==='POST'){ const body=await readJson(req); const op=body.op||'submit'; if(op==='submit'){ if(!me)return json(401,{error:'sign-in-required'}); const rec=await submit({...(body.item||body),submitted_by:me}); return json(200,{ok:true,item:rec}); } if(op==='decide'){ if(!ctx.isSteward)return json(403,{error:'steward-only'}); const it=await decide(body.item_id,body.decision,me); if(ctx.ledgerAppend)await ctx.ledgerAppend({kind:'curate',op:it.decision,id:it.item_id,actor:me||'steward',hash:createHash('sha256').update(`${it.decision}:${it.item_id}`).digest('hex').slice(0,16),ts:new Date().toISOString()}); return json(200,{ok:true,item:it}); } return json(400,{error:'unknown-op'}); } return json(405,{error:'method-not-allowed'}); }catch(e){ return json(400,{error:'curate-refused',detail:String(e.message||e)}); } }
