import { readFile, writeFile, rename, mkdir } from 'node:fs/promises';
import { dirname } from 'node:path';
import { createHash } from 'node:crypto';
const MEMBERS_FILE = process.env.MEMBERS_FILE || `${process.env.DATA_DIR || '/data'}/members.json`;
const ROLES=['visitor','member','steward','maintainer'];
const ALLOWED=new Set(['id','role','joined','region','contributions','status','notes']);
const FORBIDDEN=new Set(['value','secret','token','password','api_key','key','email','phone','address','dob','ssn']);
export function scrub(input){ const rec={}; for(const [k,v] of Object.entries(input||{})){ const key=String(k).toLowerCase(); if(FORBIDDEN.has(key)) throw new Error(`refused: "${k}" — no PII, no secrets`); if(!ALLOWED.has(key)) continue; rec[key]=v; } if(!rec.id) throw new Error('member requires an "id" (handle)'); if(rec.role&&!ROLES.includes(rec.role)) throw new Error(`role must be one of ${ROLES.join(', ')}`); rec.role=rec.role||'member'; rec.status=rec.status||'active'; return rec; }
async function load(){ try{ const j=JSON.parse(await readFile(MEMBERS_FILE,'utf8')); return {members:j.members||[]}; }catch{ return {members:[]}; } }
async function save(s){ await mkdir(dirname(MEMBERS_FILE),{recursive:true}).catch(()=>{}); const t=MEMBERS_FILE+'.tmp'; await writeFile(t,JSON.stringify(s,null,2)); await rename(t,MEMBERS_FILE); }
export async function listMembers(){ const {members}=await load(); return {members,count:members.length}; }
export async function joinAs(handle,region){ if(!handle)throw new Error('join requires a handle'); const s=await load(); let m=s.members.find(x=>x.id===handle); if(!m){ m=scrub({id:handle,role:'member',region,joined:new Date().toISOString()}); s.members.push(m);} await save(s); return m; }
export async function setRole(id,role){ if(!ROLES.includes(role))throw new Error(`role must be one of ${ROLES.join(', ')}`); const s=await load(); const m=s.members.find(x=>x.id===id); if(!m)throw new Error(`no member "${id}"`); m.role=role; await save(s); return m; }
export async function exportRecord(id){ const {members}=await load(); return members.find(x=>x.id===id)||null; }
export async function forget(id){ const s=await load(); const m=s.members.find(x=>x.id===id); if(!m)throw new Error(`no member "${id}"`); m.region=null; m.notes=null; m.contributions=null; m.status='forgotten'; await save(s); return {id,status:'forgotten'}; }
function readJson(req){ return new Promise(r=>{let b='';req.on('data',c=>b+=c);req.on('end',()=>{try{r(b?JSON.parse(b):{})}catch{r({})}})}); }
function sendJson(res,c,o){ res.writeHead(c,{'content-type':'application/json'}); res.end(JSON.stringify(o)); }
export async function members(req,res,ctx={}){ const json=ctx.json||((c,o)=>sendJson(res,c,o)); const me=ctx.identity&&ctx.identity.login; try{ if(req.method==='GET'){ if(!ctx.isSteward)return json(403,{error:'steward-only'}); return json(200,await listMembers()); } if(req.method==='POST'){ const body=await readJson(req); const op=body.op||'join'; if(op==='join'){ if(!me)return json(401,{error:'sign-in-required'}); const m=await joinAs(me,body.region); if(ctx.ledgerAppend)await ctx.ledgerAppend({kind:'member',op:'join',id:m.id,actor:me,ts:new Date().toISOString()}); return json(200,{ok:true,member:m}); } if(op==='export'){ if(!(ctx.isSteward||me===body.id))return json(403,{error:'self-or-steward-only'}); return json(200,{record:await exportRecord(body.id)}); } if(!ctx.isSteward)return json(403,{error:'steward-only'}); let result; if(op==='set-role')result=await setRole(body.id,body.role); else if(op==='forget')result=await forget(body.id); else return json(400,{error:'unknown-op'}); if(ctx.ledgerAppend)await ctx.ledgerAppend({kind:'member',op,id:body.id,actor:me||'steward',hash:createHash('sha256').update(`${op}:${body.id}`).digest('hex').slice(0,16),ts:new Date().toISOString()}); return json(200,{ok:true,op,result}); } return json(405,{error:'method-not-allowed'}); }catch(e){ return json(400,{error:'members-refused',detail:String(e.message||e)}); } }
