import { readFile, writeFile, rename, mkdir } from 'node:fs/promises';
import { dirname } from 'node:path';
import { createHash } from 'node:crypto';
const REGISTRY_FILE = process.env.REGISTRY_FILE || `${process.env.DATA_DIR || '/data'}/registry.json`;
const FORBIDDEN = new Set(['value','secret','token','password','passwd','apikey','api_key','key','client_secret','private_key','credential','bearer','cookie','session']);
const ALLOWED = new Set(['id','kind','service','provider','purpose','owner','env','key_id','last4','scope','created_at','rotate_by','last_used_at','status','notes','op_ref']);
function looksSecret(v){ if(typeof v!=='string')return false; return v.length>=20 && /^[A-Za-z0-9_\-./+=]{20,}$/.test(v); }
export function scrub(input){ const rec={}; for(const [k,v] of Object.entries(input||{})){ const key=String(k); if(FORBIDDEN.has(key.toLowerCase())) throw new Error(`refused: field "${key}" would store secret material — registry holds metadata only`); if(!ALLOWED.has(key)) continue; if(key==='last4'){ rec.last4=String(v).slice(-4); continue; } if(looksSecret(v)) throw new Error(`refused: value for "${key}" looks like a secret — store it in the broker, not the registry`); rec[key]=v; } if(!rec.id) throw new Error('record requires an "id"'); rec.kind=rec.kind||(rec.key_id||rec.last4||rec.scope?'credential':'service'); rec.status=rec.status||'active'; return rec; }
async function load(){ try{ const j=JSON.parse(await readFile(REGISTRY_FILE,'utf8')); return Array.isArray(j.records)?j:{records:[]}; }catch{ return {records:[]}; } }
async function save(s){ await mkdir(dirname(REGISTRY_FILE),{recursive:true}).catch(()=>{}); const t=REGISTRY_FILE+'.tmp'; await writeFile(t,JSON.stringify(s,null,2)); await rename(t,REGISTRY_FILE); }
export function dueForRotation(records,days=30){ const c=Date.now()+days*86400000; return records.filter(r=>r.rotate_by&&Date.parse(r.rotate_by)<=c&&r.status!=='revoked').map(r=>({id:r.id,service:r.service,rotate_by:r.rotate_by})); }
export async function listRegistry(){ const {records}=await load(); return {records,count:records.length,due_for_rotation:dueForRotation(records),generated_at:new Date().toISOString()}; }
export async function upsertRecord(input){ const rec=scrub(input); const s=await load(); const i=s.records.findIndex(r=>r.id===rec.id); if(i>=0)s.records[i]={...s.records[i],...rec}; else{ rec.created_at=rec.created_at||new Date().toISOString(); s.records.push(rec);} await save(s); return rec; }
export async function revokeRecord(id){ const s=await load(); const r=s.records.find(x=>x.id===id); if(!r)throw new Error(`no record "${id}"`); r.status='revoked'; await save(s); return r; }
export function reconcile(records,brokerKeyIds=[]){ const inReg=new Set(records.filter(r=>r.kind==='credential').map(r=>r.key_id).filter(Boolean)); const inBroker=new Set(brokerKeyIds); return {orphans_in_broker:[...inBroker].filter(k=>!inReg.has(k)),missing_in_broker:[...inReg].filter(k=>!inBroker.has(k)),overdue:dueForRotation(records,0)}; }
function readJson(req){ return new Promise(r=>{let b='';req.on('data',c=>b+=c);req.on('end',()=>{try{r(b?JSON.parse(b):{})}catch{r({})}})}); }
function sendJson(res,c,o){ res.writeHead(c,{'content-type':'application/json'}); res.end(JSON.stringify(o)); }
export async function registry(req,res,ctx={}){ const json=ctx.json||((c,o)=>sendJson(res,c,o)); try{ if(ctx.requireSteward){ const ok=await ctx.requireSteward(req,res); if(!ok)return; } if(req.method==='GET')return json(200,await listRegistry()); if(req.method==='POST'){ const body=await readJson(req); const op=body.op||'upsert'; const result=op==='revoke'?await revokeRecord(body.id):await upsertRecord(body.record||body); if(ctx.ledgerAppend)await ctx.ledgerAppend({kind:'registry',op,id:result.id,actor:(ctx.identity&&ctx.identity.login)||'steward',hash:createHash('sha256').update(`${op}:${result.id}`).digest('hex').slice(0,16),ts:new Date().toISOString()}); return json(200,{ok:true,op,id:result.id}); } return json(405,{error:'method-not-allowed'}); }catch(e){ return json(400,{error:'registry-refused',detail:String(e.message||e)}); } }
