#!/usr/bin/env bash
# deploy/setup-estate-mailer.sh — stand up the estate email sender in ONE command.
#
# What it does (all via YOUR authenticated CLIs — the secret never leaves your machine):
#   1. creates the Entra app "AiGovOps Estate Mailer"
#   2. adds Microsoft Graph Mail.Send (application) + grants admin consent
#   3. mints a client secret
#   4. sets the four GitHub Actions secrets the hourly workflow reads
#
# Run it where you're already signed in:
#   • Locally:  az login   (as a Global Admin in aigovops.community)  +  gh auth login
#   • Or in Azure Cloud Shell (az is pre-authed); if gh isn't there, it prints the 4 values to paste.
#
#   bash deploy/setup-estate-mailer.sh [sender@aigovops.community]
#
# The client secret is generated by Azure and piped straight into GitHub. It is never printed
# unless gh is unavailable (then it's shown once, on YOUR terminal, for manual entry). Never
# paste it into chat.
set -euo pipefail

APP_NAME="AiGovOps Estate Mailer"
SENDER="${1:-estate@aigovops.community}"
REPO="aigovops-foundation/aigovops-library-june-ken-bob"
GRAPH_APP="00000003-0000-0000-c000-000000000000"          # Microsoft Graph
MAIL_SEND_ROLE="b633e1c5-b582-4048-a93e-9f11b44c7e96"      # Mail.Send (Application)

command -v az >/dev/null || { echo "✗ Azure CLI 'az' not found. Install it, or run this in Azure Cloud Shell."; exit 1; }
az account show >/dev/null 2>&1 || { echo "✗ Not signed in. Run:  az login"; exit 1; }
TENANT=$(az account show --query tenantId -o tsv)
echo "▸ Tenant: $TENANT"

# 1) app (reuse if it already exists)
APP_ID=$(az ad app list --display-name "$APP_NAME" --query "[0].appId" -o tsv)
if [ -z "$APP_ID" ]; then
  echo "▸ Creating app '$APP_NAME'…"
  APP_ID=$(az ad app create --display-name "$APP_NAME" --sign-in-audience AzureADMyOrg --query appId -o tsv)
else
  echo "▸ Reusing existing app $APP_ID"
fi
az ad sp show --id "$APP_ID" >/dev/null 2>&1 || az ad sp create --id "$APP_ID" >/dev/null
echo "▸ App (client) ID: $APP_ID"

# 2) Mail.Send (application) + admin consent
echo "▸ Adding Microsoft Graph Mail.Send (application)…"
az ad app permission add --id "$APP_ID" --api "$GRAPH_APP" --api-permissions "${MAIL_SEND_ROLE}=Role" >/dev/null 2>&1 || true
sleep 8   # let the permission propagate before consent
echo "▸ Granting admin consent (needs Global Admin / Privileged Role Admin)…"
if ! az ad app permission admin-consent --id "$APP_ID" 2>/dev/null; then
  echo "  ⚠ Admin consent didn't complete via CLI. Grant it once in the portal:"
  echo "     Entra → App registrations → $APP_NAME → API permissions → Grant admin consent."
fi

# 3) client secret
echo "▸ Minting a client secret (24 months)…"
SECRET=$(az ad app credential reset --id "$APP_ID" --append --years 2 --query password -o tsv)

# 4) GitHub secrets
if command -v gh >/dev/null && gh auth status >/dev/null 2>&1; then
  echo "▸ Setting GitHub Actions secrets on $REPO…"
  gh secret set GRAPH_TENANT_ID     -R "$REPO" -b "$TENANT"
  gh secret set GRAPH_CLIENT_ID     -R "$REPO" -b "$APP_ID"
  gh secret set GRAPH_CLIENT_SECRET -R "$REPO" -b "$SECRET"
  gh secret set GRAPH_SENDER        -R "$REPO" -b "$SENDER"
  echo "✅ Done. All four secrets set — the hourly workflow will send on its next run."
else
  echo
  echo "  gh CLI not available — set these four in GitHub → Settings → Secrets and variables → Actions:"
  echo "    GRAPH_TENANT_ID      $TENANT"
  echo "    GRAPH_CLIENT_ID      $APP_ID"
  echo "    GRAPH_CLIENT_SECRET  $SECRET"
  echo "    GRAPH_SENDER         $SENDER"
  echo "  (This is the only time the secret is shown. It's on YOUR terminal — don't paste it into chat.)"
fi

echo
echo "  Recommended hardening (Exchange Online PowerShell) — lock the app to only '$SENDER':"
echo "    New-ApplicationAccessPolicy -AppId $APP_ID -PolicyScopeGroupId $SENDER \\"
echo "      -AccessRight RestrictAccess -Description 'AiGovOps Estate Mailer — $SENDER only'"
